# Generated by OpenVN.
# OpenVN Story Format: 0.3
# Do not edit this file manually.

label start:
    jump ovn_start_0001

label ovn_start_0001:
    "Choose."
    jump ovn_start_0002

label ovn_start_0002:
    menu:
        "Continue":
            jump ovn_ending_0001

label ovn_ending_0001:
    "Finished."
    jump ovn_ending_0002

label ovn_ending_0002:
    return
