from __future__ import annotations

import shutil
from pathlib import Path

from ...assets import AssetManifest


def render_images(manifest: AssetManifest) -> str:
    lines = ["# Generated by OpenVN.", ""]

    for name, path in sorted(manifest.backgrounds.items()):
        lines.append(f'image bg {name} = "{path}"')

    for character, poses in sorted(manifest.characters.items()):
        for pose, path in sorted(poses.items()):
            lines.append(f'image {character} {pose} = "{path}"')

    return "\n".join(lines).rstrip() + "\n"


def render_audio(manifest: AssetManifest) -> str:
    lines = ["# Generated by OpenVN.", ""]

    for name, path in sorted(manifest.music.items()):
        lines.append(f'define audio.{name} = "{path}"')

    for name, path in sorted(manifest.sfx.items()):
        lines.append(f'define audio.{name} = "{path}"')

    return "\n".join(lines).rstrip() + "\n"


def copy_assets(manifest: AssetManifest, game_dir: Path) -> None:
    for source in manifest.all_files():
        relative = source.relative_to(manifest.root)
        destination = game_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
