from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ...errors import OpenVNError


def _label(node_id: str) -> str:
    return "ovn_" + "".join(character if character.isalnum() else "_" for character in node_id)


def _quote(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def _render_node(node: dict[str, Any]) -> list[str]:
    node_type = node["type"]
    lines = [f"label {_label(node['id'])}:"]

    if node_type == "text":
        lines.append(f"    {_quote(node['text'])}")
        target = node.get("next")
        if target:
            lines.append(f"    jump {_label(target)}")
        else:
            lines.append("    return")
        return lines

    if node_type == "choice":
        lines.append("    menu:")
        for option in node["options"]:
            lines.append(f"        {_quote(option['text'])}:")
            lines.append(f"            jump {_label(option['target'])}")
        return lines

    if node_type == "jump":
        lines.append(f"    jump {_label(node['target'])}")
        return lines

    if node_type == "end":
        lines.append("    return")
        return lines

    raise OpenVNError(f"unsupported Ren'Py node type: {node_type}")


def render_script(document: dict[str, Any]) -> str:
    if document.get("format") != "openvn-story":
        raise OpenVNError("unsupported document format")
    if document.get("version") != "0.3":
        raise OpenVNError(f"unsupported OpenVN format version: {document.get('version')}")

    entry = document.get("entry")
    if not isinstance(entry, str) or not entry:
        raise OpenVNError("OpenVN story entry is missing")

    lines = [
        "# Generated by OpenVN. Do not edit manually.",
        "",
        "label start:",
        f"    jump {_label(entry)}",
        "",
    ]

    for node in document.get("nodes", []):
        lines.extend(_render_node(node))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def export_renpy_project(
    story_path: str | Path,
    output_dir: str | Path,
) -> Path:
    source = Path(story_path)
    if not source.is_file():
        raise OpenVNError(f"missing OpenVN story file: {source}")

    document = json.loads(source.read_text(encoding="utf-8"))
    output = Path(output_dir)
    game = output / "game"
    game.mkdir(parents=True, exist_ok=True)

    (game / "script.rpy").write_text(render_script(document), encoding="utf-8")
    (game / "options.rpy").write_text(
        'define config.name = _("OpenVN Export")\ndefine build.name = "openvn_export"\n',
        encoding="utf-8",
    )
    (output / "README.md").write_text(
        "# Generated Ren'Py Project\n\nOpen this directory in the Ren'Py launcher.\n",
        encoding="utf-8",
    )

    return output
