from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

from ...assets import load_asset_manifest
from ...errors import OpenVNError
from .assets import copy_assets, render_audio, render_images


def _label(node_id: str) -> str:
    normalized = "".join(character.lower() if character.isalnum() else "_" for character in node_id)
    while "__" in normalized:
        normalized = normalized.replace("__", "_")
    normalized = normalized.strip("_")
    if not normalized:
        raise OpenVNError(f"cannot create Ren'Py label from node id: {node_id!r}")
    return f"ovn_{normalized}"


def _quote(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def _validate_document(document: dict[str, Any]) -> None:
    if document.get("format") != "openvn-story":
        raise OpenVNError("unsupported document format")
    if document.get("version") not in {"0.3", "0.4"}:
        raise OpenVNError(f"unsupported OpenVN format version: {document.get('version')}")

    entry = document.get("entry")
    nodes = document.get("nodes")
    if not isinstance(entry, str) or not entry:
        raise OpenVNError("OpenVN story entry is missing")
    if not isinstance(nodes, list) or not nodes:
        raise OpenVNError("OpenVN story has no nodes")

    node_ids: list[str] = []
    for node in nodes:
        node_id = node.get("id")
        if not isinstance(node_id, str) or not node_id:
            raise OpenVNError("OpenVN node id is missing")
        node_ids.append(node_id)

    if len(node_ids) != len(set(node_ids)):
        raise OpenVNError("OpenVN story contains duplicate node IDs")

    labels = [_label(node_id) for node_id in node_ids]
    if len(labels) != len(set(labels)):
        raise OpenVNError("OpenVN node IDs collide as Ren'Py labels")

    known = set(node_ids)
    if entry not in known:
        raise OpenVNError(f"unknown story entry: {entry}")

    linear_types = {"text", "scene", "show", "hide", "music", "sound"}
    for node in nodes:
        node_type = node.get("type")
        if node_type in linear_types:
            target = node.get("next")
            if target is not None and target not in known:
                raise OpenVNError(f"unknown {node_type} target: {target}")
        elif node_type == "choice":
            options = node.get("options")
            if not isinstance(options, list) or not options:
                raise OpenVNError(f"choice node {node['id']} has no options")
            for option in options:
                target = option.get("target")
                if target not in known:
                    raise OpenVNError(f"unknown choice target: {target}")
        elif node_type == "jump":
            target = node.get("target")
            if target not in known:
                raise OpenVNError(f"unknown jump target: {target}")
        elif node_type == "end":
            continue
        else:
            raise OpenVNError(f"unsupported Ren'Py node type: {node_type}")


def _render_next(lines: list[str], target: str | None) -> list[str]:
    lines.append(f"    jump {_label(target)}" if target else "    return")
    return lines


def _render_node(node: dict[str, Any]) -> list[str]:
    node_type = node["type"]
    lines = [f"label {_label(node['id'])}:"]

    if node_type == "text":
        lines.append(f"    {_quote(node.get('text', ''))}")
        return _render_next(lines, node.get("next"))

    if node_type == "scene":
        lines.append(f"    scene bg {node['background']}")
        return _render_next(lines, node.get("next"))

    if node_type == "show":
        lines.append(f"    show {node['character']} {node['pose']}")
        return _render_next(lines, node.get("next"))

    if node_type == "hide":
        lines.append(f"    hide {node['character']}")
        return _render_next(lines, node.get("next"))

    if node_type == "music":
        if node.get("track") is None:
            lines.append("    stop music")
        else:
            lines.append(f"    play music audio.{node['track']}")
        return _render_next(lines, node.get("next"))

    if node_type == "sound":
        lines.append(f"    play sound audio.{node['sound']}")
        return _render_next(lines, node.get("next"))

    if node_type == "choice":
        lines.append("    menu:")
        for option in node["options"]:
            lines.append(f"        {_quote(option['text'])}:")
            lines.append(f"            jump {_label(option['target'])}")
        return lines

    if node_type == "jump":
        lines.append(f"    jump {_label(node['target'])}")
        return lines

    if node_type == "end":
        lines.append("    return")
        return lines

    raise OpenVNError(f"unsupported Ren'Py node type: {node_type}")


def render_script(document: dict[str, Any]) -> str:
    _validate_document(document)
    lines = [
        "# Generated by OpenVN.",
        f"# OpenVN Story Format: {document['version']}",
        "# Do not edit this file manually.",
        "",
        "label start:",
        f"    jump {_label(document['entry'])}",
        "",
    ]
    for node in document["nodes"]:
        lines.extend(_render_node(node))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def export_renpy_project(
    story_path: str | Path,
    output_dir: str | Path,
    *,
    clean: bool = False,
) -> Path:
    source = Path(story_path)
    if not source.is_file():
        raise OpenVNError(f"missing OpenVN story file: {source}")

    project_root = source.parent
    manifest = load_asset_manifest(project_root)
    output = Path(output_dir)
    if clean and output.exists():
        shutil.rmtree(output)

    document = json.loads(source.read_text(encoding="utf-8"))
    game = output / "game"
    game.mkdir(parents=True, exist_ok=True)

    (game / "script.rpy").write_text(render_script(document), encoding="utf-8")
    (game / "images.rpy").write_text(render_images(manifest), encoding="utf-8")
    (game / "audio.rpy").write_text(render_audio(manifest), encoding="utf-8")
    (game / "options.rpy").write_text(
        'define config.name = _("OpenVN Export")\ndefine build.name = "openvn_export"\n',
        encoding="utf-8",
    )
    copy_assets(manifest, game)
    (output / "README.md").write_text(
        "# Generated Ren'Py Project\n\n"
        f"Generated from OpenVN Story Format {document['version']}.\n",
        encoding="utf-8",
    )
    return output
