from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

from .errors import OpenVNError

PACKAGE_FORMAT = "openvn-fsuae-package"
PACKAGE_VERSION = "0.2"
DEFAULT_VOLUME = "DH0"
DEFAULT_APP_DIR = "OpenVN"
DEFAULT_PLAYER = "runtime/openvn-player"


def _copy_player(player: Path, destination: Path) -> None:
    if not player.is_file():
        raise OpenVNError(f"missing Amiga player executable: {player}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(player, destination)
    destination.chmod(destination.stat().st_mode | 0o111)


def _build_player(
    *,
    repository: Path,
    amiga_package: Path,
    toolchain_file: Path,
    build_dir: Path,
) -> Path:
    if not toolchain_file.is_file():
        raise OpenVNError(f"missing CMake toolchain file: {toolchain_file}")

    source = repository / "runtimes" / "amiga-native"
    story = amiga_package / "story" / "story.generated.c"
    assets = amiga_package / "story" / "assets.generated.c"
    command = [
        "cmake",
        "-S",
        str(source),
        "-B",
        str(build_dir),
        f"-DCMAKE_TOOLCHAIN_FILE={toolchain_file}",
        f"-DOPENVN_GENERATED_STORY_SOURCE={story}",
        f"-DOPENVN_GENERATED_ASSETS_SOURCE={assets}",
    ]
    try:
        subprocess.run(command, check=True)
        subprocess.run(
            ["cmake", "--build", str(build_dir), "--target", "openvn-player"],
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        raise OpenVNError(f"failed to build Amiga player: {exc}") from exc

    executable = build_dir / "openvn-player"
    if not executable.is_file():
        raise OpenVNError(f"Amiga build did not produce {executable}")
    return executable


def _startup_sequence() -> str:
    """Return a self-contained AmigaDOS bootstrap.

    The player must run with DH0:OpenVN as its current directory because
    generated asset paths are relative to the application root.
    """
    return "\n".join(
        [
            "; Generated by OpenVN. Do not edit generated output.",
            "; Minimal bootstrap: no C:, S:, LIBS:, or ARexx commands required.",
            "CD DH0:OpenVN",
            DEFAULT_PLAYER,
            "",
        ]
    )


def _fsuae_config() -> str:
    return "\n".join(
        [
            "[fs-uae]",
            "amiga_model = A500",
            "chip_memory = 1024",
            "slow_memory = 1792",
            "hard_drive_0 = harddrive",
            f"hard_drive_0_label = {DEFAULT_VOLUME}",
            "automatic_input_grab = 0",
            "window_width = 960",
            "window_height = 768",
            "",
        ]
    )


def package_fsuae(
    *,
    repository: str | Path,
    amiga_package: str | Path,
    output_dir: str | Path,
    player: str | Path | None = None,
    toolchain_file: str | Path | None = None,
    clean: bool = False,
) -> Path:
    repo = Path(repository).resolve()
    package = Path(amiga_package).resolve()
    output = Path(output_dir).resolve()

    if not (package / "manifest.json").is_file():
        raise OpenVNError(f"missing Amiga package manifest: {package / 'manifest.json'}")
    if player is None and toolchain_file is None:
        raise OpenVNError("provide --player or --toolchain-file for FS-UAE packaging")
    if player is not None and toolchain_file is not None:
        raise OpenVNError("use either --player or --toolchain-file, not both")

    if clean and output.exists():
        shutil.rmtree(output)

    harddrive = output / "harddrive"
    bundled_package = harddrive / DEFAULT_APP_DIR
    bundled_package.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(package, bundled_package, dirs_exist_ok=True)

    if player is not None:
        executable = Path(player).resolve()
    else:
        executable = _build_player(
            repository=repo,
            amiga_package=package,
            toolchain_file=Path(toolchain_file).resolve(),
            build_dir=output / "build-amiga",
        )
    _copy_player(executable, bundled_package / DEFAULT_PLAYER)

    startup = harddrive / "S" / "Startup-Sequence"
    startup.parent.mkdir(parents=True, exist_ok=True)
    startup.write_text(_startup_sequence(), encoding="ascii")

    config = output / "OpenVNDemo.fs-uae"
    config.write_text(_fsuae_config(), encoding="utf-8")
    (output / "README.txt").write_text(
        "Open OpenVNDemo.fs-uae in FS-UAE. The generated hard drive is a "
        "self-contained OpenVN application volume and its Startup-Sequence "
        "does not require commands in C:. A legally obtained Kickstart ROM "
        "or a compatible replacement ROM is still required.\n",
        encoding="utf-8",
    )
    (output / "package.json").write_text(
        json.dumps(
            {
                "format": PACKAGE_FORMAT,
                "version": PACKAGE_VERSION,
                "configuration": "OpenVNDemo.fs-uae",
                "harddrive": "harddrive",
                "volume": DEFAULT_VOLUME,
                "application": f"harddrive/{DEFAULT_APP_DIR}",
                "player": f"harddrive/{DEFAULT_APP_DIR}/{DEFAULT_PLAYER}",
                "startup_sequence": "harddrive/S/Startup-Sequence",
                "startup_mode": "direct-player",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return output
